In [1]:
# Linear Regression
# First compute the required features and after to a linear regression of them

In [1]:
import pandas as pd
import numpy as np
import csv
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
dfTrain = pd.read_csv('datasets/train.csv', delimiter=',')
X_raw = dfTrain.iloc[:,2:]
y = dfTrain.iloc[:,1]

In [3]:
print(X_raw)
print(y)
print(len(X_raw),len(y))

       x1    x2    x3    x4    x5
0    0.02  0.05 -0.09 -0.43 -0.08
1   -0.13  0.11 -0.08 -0.29 -0.03
2    0.08  0.06 -0.07 -0.41 -0.03
3    0.02 -0.12  0.01 -0.43 -0.02
4   -0.14 -0.12 -0.08 -0.02 -0.08
..    ...   ...   ...   ...   ...
695  0.31 -0.09  0.04 -0.09  0.03
696 -0.26 -0.01  0.02 -0.40  0.05
697 -0.27 -0.22 -0.01 -0.32 -0.05
698  0.19  0.11 -0.05 -0.27 -0.04
699 -0.09 -0.09 -0.06 -0.41 -0.06

[700 rows x 5 columns]
0     -6.822679
1     -6.326290
2     -9.302728
3     -7.371893
4     -6.027647
         ...
695   -6.147394
696   -6.214899
697   -6.841341
698   -6.523371
699   -5.676683
Name: y, Length: 700, dtype: float64
700 700

In [4]:
#Compute the features for each entry
#linear feature
X_lin = X_raw.copy()
#quadratic feature
X_sq = np.square(X_raw.copy())
#exponential feature
X_exp = np.exp(X_raw.copy())
#cos feature
X_cos = np.cos(X_raw.copy())

In [79]:
col_names = []
for i in range(1,21):
    col_names.append('phi%s'%str(i))

In [80]:
col_names

['phi1',
 'phi2',
 'phi3',
 'phi4',
 'phi5',
 'phi6',
 'phi7',
 'phi8',
 'phi9',
 'phi10',
 'phi11',
 'phi12',
 'phi13',
 'phi14',
 'phi15',
 'phi16',
 'phi17',
 'phi18',
 'phi19',
 'phi20']

In [81]:
# concatenate
X = pd.concat([X_lin, X_sq, X_exp, X_cos], axis=1)

In [83]:
X.columns = col_names

In [84]:
# add the constant column
X['phi21'] = np.ones(len(X_raw['x1']))

In [85]:
X

,phi1,phi2,phi3,phi4,phi5,phi6,phi7,phi8,phi9,phi10,...,phi12,phi13,phi14,phi15,phi16,phi17,phi18,phi19,phi20,phi21
0,0.02,0.05,-0.09,-0.43,-0.08,0.0004,0.0025,0.0081,0.1849,0.0064,...,1.051271,0.913931,0.650509,0.923116,0.999800,0.998750,0.995953,0.908966,0.996802,1.0
1,-0.13,0.11,-0.08,-0.29,-0.03,0.0169,0.0121,0.0064,0.0841,0.0009,...,1.116278,0.923116,0.748264,0.970446,0.991562,0.993956,0.996802,0.958244,0.999550,1.0
2,0.08,0.06,-0.07,-0.41,-0.03,0.0064,0.0036,0.0049,0.1681,0.0009,...,1.061837,0.932394,0.663650,0.970446,0.996802,0.998201,0.997551,0.917121,0.999550,1.0
3,0.02,-0.12,0.01,-0.43,-0.02,0.0004,0.0144,0.0001,0.1849,0.0004,...,0.886920,1.010050,0.650509,0.980199,0.999800,0.992809,0.999950,0.908966,0.999800,1.0
4,-0.14,-0.12,-0.08,-0.02,-0.08,0.0196,0.0144,0.0064,0.0004,0.0064,...,0.886920,0.923116,0.980199,0.923116,0.990216,0.992809,0.996802,0.999800,0.996802,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0.31,-0.09,0.04,-0.09,0.03,0.0961,0.0081,0.0016,0.0081,0.0009,...,0.913931,1.040811,0.913931,1.030455,0.952334,0.995953,0.999200,0.995953,0.999550,1.0
696,-0.26,-0.01,0.02,-0.40,0.05,0.0676,0.0001,0.0004,0.1600,0.0025,...,0.990050,1.020201,0.670320,1.051271,0.966390,0.999950,0.999800,0.921061,0.998750,1.0
697,-0.27,-0.22,-0.01,-0.32,-0.05,0.0729,0.0484,0.0001,0.1024,0.0025,...,0.802519,0.990050,0.726149,0.951229,0.963771,0.975897,0.999950,0.949235,0.998750,1.0
698,0.19,0.11,-0.05,-0.27,-0.04,0.0361,0.0121,0.0025,0.0729,0.0016,...,1.116278,0.951229,0.763379,0.960789,0.982004,0.993956,0.998750,0.963771,0.999200,1.0
699,-0.09,-0.09,-0.06,-0.41,-0.06,0.0081,0.0081,0.0036,0.1681,0.0036,...,0.913931,0.941765,0.663650,0.941765,0.995953,0.995953,0.998201,0.917121,0.998201,1.0

In [86]:
len(X.columns)

21

In [87]:
#Now that we have all the right features, we spli into train and test data
XTrain, XTest, yTrain, yTest = train_test_split(X, y, train_size=0.8)
XTrain.head()

,phi1,phi2,phi3,phi4,phi5,phi6,phi7,phi8,phi9,phi10,...,phi12,phi13,phi14,phi15,phi16,phi17,phi18,phi19,phi20,phi21
624,0.06,0.03,-0.02,-0.09,-0.10,0.0036,0.0009,0.0004,0.0081,0.0100,...,1.030455,0.980199,0.913931,0.904837,0.998201,0.999550,0.999800,0.995953,0.995004,1.0
464,-0.05,-0.22,-0.13,-0.38,-0.08,0.0025,0.0484,0.0169,0.1444,0.0064,...,0.802519,0.878095,0.683861,0.923116,0.998750,0.975897,0.991562,0.928665,0.996802,1.0
28,0.07,0.11,0.01,-0.32,-0.07,0.0049,0.0121,0.0001,0.1024,0.0049,...,1.116278,1.010050,0.726149,0.932394,0.997551,0.993956,0.999950,0.949235,0.997551,1.0
241,-0.03,-0.03,0.04,-0.43,-0.07,0.0009,0.0009,0.0016,0.1849,0.0049,...,0.970446,1.040811,0.650509,0.932394,0.999550,0.999550,0.999200,0.908966,0.997551,1.0
459,0.01,0.05,-0.01,0.11,-0.08,0.0001,0.0025,0.0001,0.0121,0.0064,...,1.051271,0.990050,1.116278,0.923116,0.999950,0.998750,0.999950,0.993956,0.996802,1.0

In [88]:
# fit the model = linear regression
model = LinearRegression()
model.fit(XTrain, yTrain)

LinearRegression()

In [89]:
#prediction and RMSE
yTestPred = model.predict(XTest)
print("RMSE: %.2e" %(np.sqrt(metrics.mean_squared_error(yTest, yTestPred))))

RMSE: 2.26e+00

In [62]:
#coefficients from the linear regression
coefficients = model.coef_
print(coefficients)
print("the lenght is ",len(coefficients))

[  177.66504275  -108.1780653     71.89949752   157.06187068
 -1993.95577074 -1541.18973591  -333.34796452  1535.36279697
  -441.09632459  3478.67048757  -176.5000328    105.67675981
   -73.69977937  -154.70625659  1998.90042233 -3268.81265327
  -576.17440697  3005.17475203 -1042.74353028  8818.49853787
     0.        ]
the lenght is  21

In [63]:
type(coefficients[0])

numpy.float64

In [64]:
# in the csv submit file we need to put the coefficients of the linear regression
df = pd.DataFrame(data={"col1": coefficients})
df.to_csv("submit_fe.csv", sep=',',index=False, header=None)